all: bubble insertion selection merge
	
bubble: BubbleSort.cpp
	g++ BubbleSort.cpp -o bubble

insertion: InsertionSort.cpp
	g++ InsertionSort.cpp -o insertion

selection: SelectionSort.cpp
	g++ SelectionSort.cpp -o selection

merge: MergeSort.cpp
	g++ MergeSort.cpp -o merge

clean:
	rm bubble insertion selection merge