all: hashTable1 hashTable2 hashTable3 hashTable4 compare

hashTable1: hashTable1.cpp
	g++ hashTable1.cpp -o hashTable1

hashTable2: hashTable2.cpp
	g++ hashTable2.cpp -o hashTable2

hashTable3: hashTable3.cpp
	g++ hashTable3.cpp -o hashTable3

hashTable4: hashTable4.cpp
	g++ hashTable4.cpp -o hashTable4

compare: compare.cpp
	g++ compare.cpp -o compare

clean:
	rm hashTable1 hashTable2 hashTable3